shell tmux new-session \; set-option destroy-unattached on
# shell $HOME/.config/kitty/smart-tmux.sh

confirm_os_window_close 0

# Tab bar
tab_bar_edge top
tab_bar_align left
tab_bar_style custom
tab_bar_min_tabs 1
tab_activity_symbol none
bell_on_tab no
tab_separator ""
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_title_template "{index}"  
active_tab_font_style   bold

# Keybinds
map ctrl+shift+x launch --type=overlay ~/.config/kitty/kill_tmux_and_close.sh

# Theme
include ~/.config/kitty/themes/rose-pine/rose-pine.conf
